### ISSUE TITLE
About using custom cell in table view

### ISSUE THREAD

**Issue by PayalUmraliya** [alexbumbu/ABMenuTableViewCell#5]
Hi,This is not an issue but new upgrade in ABMenuTableViewCell

 i just integrated AB cell Menu view custom style in my app . i need to use this library with custom cell.I tried as below in ABMenuTableViewCell file

@interface ABMenuTableViewCell : UITableViewCell

@property (nonatomic, assign) UIView *rightMenuView;
@property (strong, nonatomic) IBOutlet UILabel *lblInformationText;

@end

But it gives nothing in table view cell.Please help in this case.

**Comment by alexbumbu** [comment]
Hi! 

Just updated the `SampleProject` for showing a simple example on how you can setup the cells using Interface Builder and how you can subclass `ABMenuTableViewCell`. Look for `CustomMenuTableViewCell` implementation. 

Hope this helps and thanks for the interest in using this project :).

**Comment by PayalUmraliya** [comment]
One more thing , If i swipe left the cell and again swipe next cell than previous cell should hide those two buttons more and delete means reload it self. So to reload that previously opened cell in which file should i make changes ? or any solution from your side ?

**Comment by alexbumbu** [comment]
I've made the changes so the behaviour is similar to default cells and the menu is dismissed when another cell registers a tap or swipe. Just add the content of the ABMenuTableViewCell folder to your project and it should work.
