### ISSUE TITLE
Slider issue

### ISSUE THREAD

**Issue by Beauro** [alexbumbu/ABMenuTableViewCell#6]
Hi Alex,

We have tried integrating the ABMenu into our project.  We find if we don't implement the UITableView:editActionsForRowAtIndexPath then the menu will not appear; however, this also means that the views for the actions appear underneath the menu too, which is not desirable.  Also if we don't implement UITableView:editActionsForRowAtIndexPath, then the menu just floats on top of the cell or doesn't appear at all.

Any help would be appreciated, thanks in advance!

Best,

Beauro

**Comment by Beauro** [comment]
Just a quick one, I followed the example project on creating the cells via interface builder.

**Comment by alexbumbu** [comment]
Hi Beauro,

ABMenuTableViewCell is designed to work without implementing `(BOOL)tableView: canEditRowAtIndexPath:` and if you follow the SampleProject you can see it's not implemented. 

I need more info to be able to figure out what could be the issue, also a screenshot would be great. Right now I can only think of an constraints issue for the buttons in the menu view.

p.s. What iOS version are you testing on?

**Comment by Beauro** [comment]
Hi Alex,

Yeah I saw that you hadn't implemented tableView:canEditRowAtIndexPath, but once it was implemented then the menu started sliding out. Prior to that, no sliding occurred at all, or the Menu would always be rendering on the far right of the cell.

I was using constraints in the xib where I'd designed the menu, but have since removed all constraints, but this didn't help unfortunately.

We are testing with iOS 8 & 9.

Here is a screenshot, you can see the text underneath the menu for the edit action.

![image](https://cloud.githubusercontent.com/assets/18630082/17076702/500403f0-50fc-11e6-83eb-680c8c632de5.jpg)

Let me know what other information you need.

Thanks!

Best,

Beauro

**Comment by alexbumbu** [comment]
Tried with a new project and couldn't reproduce the no sliding issue. Are you using some gesture recognizers that could conflict with ABMenuTableViewCell pan gesture recognizer?

**Comment by Beauro** [comment]
Hi Alex,

No, we don't add any other gesture recognisers in the cell, or its super
views; can't see any that would conflict with the cells' gesture recogniser.

We'll investigate future in the next couple of days and let you know how we
go.

Best,

J

**Comment by alexbumbu** [comment]
closed, due to lack of further info

**Comment by Beauro** [comment]
Hi Alex,

Sorry for late reply.  We ended up going with our own implementation, sorry
we couldn't provide any further information regarding the issue we were
experiencing.

All the best.

Nat
