### ISSUE TITLE
Error: #import objc/objc-runtime.h file not found

### ISSUE THREAD

**Issue by pillade** [alexbumbu/ABMenuTableViewCell#8]
The error happens when you try to archive the project in VisibleMenuCell category. The solution is to replace #import objc/objc-runtime.h for #import objc/runtime.h. @alexbumbu Do you want me to generate a new pull request with this solution? Do you have any other solution? 

Thanks

**Comment by alexbumbu** [comment]
Thanks for looking into it. Really appreciate if you can generate a new pull request with the solution.

**Comment by pillade** [comment]
Done

**Comment by alexbumbu** [comment]
Great, I've merged the pull request. Thanks for helping with the issue!
